### PR TITLE
New Features & Bug Fixes & Polishing the Code

### PR DESCRIPTION
**Pull request by ProIcons**
-Fixed Memory Leak caused by interceptor.
-Fixed Date Inconsistency by adding TmdbDate to all entities.
-Introduced TmdbLocale for better language handling.
-Language iso code name fields simplified to language and country.
-Modified Country class to work with TmdbLocale
-Introduced Language class for language handling.
-Replaced unnecessary Static maps from Enums with SerializedName annotation.
-Removed unnecessary Handlers from GsonBuilder after reworking of the Enums.
-Reworked of Release entity.
-ITmdbIdentifiedEntity interface introduced for entity grouping
-BaseCompany, BaseMember, BasePerson, BaseKeyword, Genre, Network implements ITmdbIdentifiedEntity
-DiscoverFilter now accepts ITmdbIdentifiedEntity entities for with_cast, with_crew, with_genres, with_keywords, with_networks, with_companies, without_genres and with_people fields.
-Fixed I/O operation tests on AccountTest.
-Reworked tests to comply with latest changes
-Introduced new tests for new utilities.
-Moved TmdbDate, DiscoverFilter, DiscoverMovieBuilder, DiscoverTvBuilder, AppendToResponse to utils package.
-Removed SpokenLanguage entity, since Language util is used in its place
-Removed TmdbInvalidAcceptHeaderException since is the requests are managed by the library.
-Added new endpoints on services with the creation of TmdbLocale, to be more user-friendly and omit unnecessary arguments.
-Some endpoints of the services which are using language field as string marked as deprecated for removal in the next version.
-Separator Enum moved out of DiscoverFilter util.
-Added CombinedSerializer on TmdbHelper for both serialize and
deserialize process

### CODE REVIEW

**Comment by UweTrottmann** [comment]
+4,387 −763 line changes, 😓... Could you please break up the changes into separate pull requests. You already have a nice list of what has changed, try to pick related changes and put them into their own pull request. Otherwise this is impossibly hard to review.

**Comment by ProIcons** [comment]
Like i mentioned some months ago i'm abit inexperienced with git. Let's say i have my branch as it is. how can i split the changes?

**Comment by ProIcons** [comment]
Most changes besides the Interceptor ones, are linked to each other. for instance i made the new endpoints after adding tmdbdate, also tmdbhelper modified for all the changes, so do the tests
 
if i'm about to split changes, i will have so much rework to do. every change made is on the message,y ou could checkout the pr and check them from your ide instead of github. you will see it's easier this way.

**Comment by ProIcons** [comment]
Most of the lines you see are the new endpoints. Crucial changes are bellow 500 lines. 

So you can just ignore all the ServiceChanges, and get to them later... please :P don't make do this all over again i'm tired

**Comment by UweTrottmann** [comment]
See https://stackoverflow.com/a/6217314

Sorry that this means more work for you, but my time is also limited. This is a hard lesson in software engineering and version control: you need to plan your changes ahead of time and make sure to make your commits fine-grained enough. Especially if you want to contribute to other projects it is a useful skill to be able to break up your changes into digestible pieces.

**Pull request closed without merging**
