### PR TITLE
Adding trending endpoint

### PR DESCRIPTION
**Pull request by gabrielsme**

### CODE REVIEW

**Comment by ProIcons** [comment]
You should adjust your formatter to the project's format settings.

**Comment by gabrielsme** [comment]
> You should adjust your formatter to the project's format settings.

Done

**Comment by UweTrottmann** [comment]
Thanks! I'll have a look once I make time for this.

**Comment by andrew-bengier** [comment]
@UweTrottmann just curious if you have time for this PR? (Also - BIG THANKS, this is a really well written and super useful API ) 👍

**Comment by UweTrottmann** [comment]
Will be released with `2.9.0` in a few hours.

**Pull request merged**
