### PR TITLE
Add VideoType and fix some issues

### LINKED ISSUE #49: Find Results
Find results returns Movie , Person, TvSeason, TvEpisode where it should return BaseMovie, BasePerson, BaseTvSeason, BaseTvEpisode

### LINKED ISSUE #50: TMDb Unsynced Servers
As [Travis Bell mentioned on TMDb Forums](https://www.themoviedb.org/talk/5939ccdfc3a36823440016f3?page=2#599312bc9251417bf601324c) their servers are unsynced. So there are cases that Throttler will fail.

### LINKED ISSUE #51: TaggedImage Entity Missing Fields
TaggedImage Entity Missing title, overview and release_date fields, and having an invalid field image_type

### LINKED ISSUE #52: On Video entity type field can be ENUM
On Video entity type field can be enum since it gets only specific values, "Trailer","Teaser","Clip","Featurette","Opening Credits"

### LINKED ISSUE #53: On TestData Actor's Origin place has been updated
On TestData Actor's Origin place has been updated and used the english translation as was intended.

### PR DESCRIPTION
**Pull request by UweTrottmann**
Note: this replaces #54 

-Fixes #49
-Fixes #50
-Fixes #51
-Fixes #52
-Fixes #53

### CODE REVIEW

**Comment by ProIcons** [comment]
Should i open new pr with the other changes? Such as tmdblocale? And the endpoints?

**Comment by UweTrottmann** [comment]
Yes. But please separate all the related changes into a separate pull request instead of one large one (so one for locale, one for new endpoints, ...). `git rebase -i` is your friend.

**Comment by ProIcons** [comment]
How do i separate prs with rebase? :/ i mean rebase if for commit refactoring, isn't it?

**Comment by UweTrottmann** [comment]
Sorry to confuse you, just disregard my comment. Just make sure to separate your changes into separate pull requests.

**Pull request merged**
