### PR TITLE
Added missing field episode_count, fixed List items type

### PR DESCRIPTION
**Pull request by stavangr**

### CODE REVIEW

**Comment by UweTrottmann** [comment]
Thanks. However, can not merge this before the following is addressed:
- I do not see the API returning `episode_count` for a season. Can you add a test to show where that might happen?
- Lists only contain movies [according to the API v3 docs](https://developers.themoviedb.org/3/lists/get-list-details). Did you maybe confuse this [with v4 of the API](https://developers.themoviedb.org/4/list/get-list)?

**Comment by stavangr** [comment]
You're right i didn't check the tv_seasons. However episode_count it's in the [tv api ](https://developers.themoviedb.org/3/tv/get-tv-details). Maybe it should be moved to the Tv_season entity instead?

In the v3 docs schema there's only movies but i tried requesting a [list containing tv shows](https://www.themoviedb.org/list/62157) and i works. Maybe the documentation isn't updated...

**Comment by UweTrottmann** [comment]
Could you then please adjust accordingly and modify/add tests (e.g. modify the test list ID to one that contains TV shows).

If you don't make any changes to this pull request in a while I will have a look myself. Thanks!

**Comment by stavangr** [comment]
ok, i've modified the test data.

**Comment by UweTrottmann** [comment]
You did not actually test the new `episode_count` field, added that for you. Changes released with `1.8.4`.

**Pull request merged**
